### ISSUE TITLE
Output of speaker order wrong?

### ISSUE THREAD

**Issue by XuDongHecs** [kaituoxu/TasNet#2]
I found the label is [spk1,spk2],but output is [spk2,spk1].
can you help me to understand this question?

**Comment by kaituoxu** [comment]
The order of speaker in output is not fixed, it maybe [spk1, spk2] or [spk2, spk1].
It's a common problem in source separation, and permutation invariant training (PIT) is introduced to solve this problem.

**Comment by XuDongHecs** [comment]
thanks for your reply!
your conv-tasnet  introduced permutation invariant training (PIT)?

**Comment by XuDongHecs** [comment]
is the order stable?

**Comment by kaituoxu** [comment]
1. My TasNet and Conv-TasNet both support PIT.
2. It's not fixed, so the order is not stable.
